server:
  port: 80

spring:
  application:
    name: KBoard

  thymeleaf:
    prefix: classpath:/templates/views/
    cache: false #spring.thymeleaf.cache

  # datasource 설정. MYSQL 등 spring-jdbc 사용 시 아래 정보 없으면 서버 가동 시 에러.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${rds.username}
    password: ${rds.password}

  # security
  security:
    user:
      name: user
      password: 1234

    # Oauth2 client
    oauth2:
      client:
        registration:
          google:
            client-id: xxxxxxx
            client-secret: xxxxxxxx
            scope:
              - email
              - profile

          facebook:
            client-id: xxxxxxxx
            client-secret: xxxxxxxx
            scope:
              - email
              - public_profile

          naver:
            client-id: xxxxxxxxx
            client-secret: xxxxxxxxx
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: xxxxxxxxxxxx

        #provider 제공
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  servlet:
    multipart: # 파일 크기 제한 설정
      max-file-size: 5MB
      max-request-size: 10MB

# MyBatis 매퍼(mapper) 파일(*.xml) 위치 설정
# src/main/resources(classpath) 이하의 경로 지정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

app:
  #페이징 세팅값
  pagination:
    write_pages: 10 # 기본 write_pages 값. 한 [페이징] 당 몇개의 페이지가 표시되나
    page_rows: 10 # 기본 page_rows 값.  한 '페이지'에 몇개의 글을 리스트 할것인가?

  #파일 업로드 경로
  upload:
    path: upload

  #Oauth2
  oauth2:
    password: 1234 # 보안주의!

    #kakao 로그인 관련 세팅값
    kakao:
      client-id: xxxxxxxx # 앱 키
      redirect-uri: xxxxxxx # Redirect URI
      token-uri: https://kauth.kakao.com/oauth/token # access token
      user-info-uri: https://kapi.kakao.com/v2/user/me # 사용자 profile 요청