# ?? ??
server:
  port: 80

spring:
  application:
    name: KBoard

  thymeleaf:
    prefix: classpath:/templates/views/
    cache: false

  # datasource ??. MySQL ? spring-jdbc ??? ?? ?? ??? ????? ??.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.post}/${rds.db.name}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: user2502
    password: 1234

  # security
  security:
    user:
      name: user
      password: 1234

    # OAuth2 client
    oauth2:
      client:
        registration:
          google:
            client-id: xxxxx
            client-secret: xxxxxx
            scope:  # 접근할수 있는 사용자 프로필 정보. ※설정되어 있지 않으면 loadUser() 는 호출되지 않는다
              - email
              - profile
          facebook:
            client-id: xxxxx
            client-secret: xxxxx
            scope:  # 접근할수 있는 사용자 프로필 정보. ※설정되어 있지 않으면 loadUser() 는 호출되지 않는다
              - email
              - public_profile

          naver:
            client-id: xxxxxx
            client-secret: xxxxx
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: xxxxxxx

        # provider 제공
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


  servlet:
    multipart:
      # 파일 크기 제한 설정
      max-file-size: 5MB
      max-request-size: 10MB

# MyBatis ??(mapper) ??(*.xml) ?? ??
# src/main/resources ??? ?? ??
mybatis:
  mapper-locations: classpath:mapper/**/*.xml


app:
  # 페이징 세팅값
  pagination:
    write_pages: 10 # 기본 write_pages 값. 한 [페이징] 당 몇개의 페이지가 표시되나
    page_rows: 10 # 기본 page_rows 값.  한 '페이지'에 몇개의 글을 리스트 할것인가?

  # 파일 업로드 경로
  upload:
    path: upload

  # OAuth2
  oauth2:
    password: 1234   # 보안주의!

    # Kakao 로그인 관련 세팅값
    kakao:
      client-id: xxxxxx  # 앱 키
      redirect-uri: xxxxxx  # Redirect URI
      token-uri: https://kauth.kakao.com/oauth/token   # access token 요청 URI
      user-info-uri: https://kapi.kakao.com/v2/user/me  # 사용자 profile 요청







